### ISSUE TITLE
时间尺度问题

### ISSUE THREAD

**Issue by liujun3660105** [zmofei/coronavirus-2019-demo#1]
1. 原始数据中，数据库是如何设计的，因为有时间尺度，时间字段怎么存储的？
2.随着时间的变化，填色图怎么更新的，其实这和从后端返回来的数据有关。其实填色图这个source不可能把每天的数据都放在矢量切片中，请问具体是怎么实现的？
3.原始数据能否共享？

**Comment by zmofei** [comment]
####  1. 原始数据中，数据库是如何设计的，因为有时间尺度，时间字段怎么存储的？

原始数据中，我们是按照天的维度存储数据的，每天每个城市/省份/国家会有一份数据，只有当天的数据是实时更新的，但是会在第二天存储为一份固定的值。
表结构可以参考如下，按照Date去Select数据

Name | Id | Pid | Date | Confrimed | Recover
-- | -- | -- | -- | -- | --
China | 1 | - | 2020/02/05 | 100 | 100
China | 1 | - | 2020/02/06 | 101 | 101
  |   |   |   |   |  
Anhui | 101 | 1 | 2020/02/05 | 50 | 30
Anhui | 101 | 1 | 2020/02/06 | 51 | 31
  |   |   |   |   |  
Hefei | 1001 | 101 | 2020/02/05 | 10 | 11
Hefei | 1001 | 101 | 2020/02/06 | 12 | 12
> 以上非后台真实数据结构，供参考

####  2.随着时间的变化，填色图怎么更新的，其实这和从后端返回来的数据有关。其实填色图这个source不可能把每天的数据都放在矢量切片中，请问具体是怎么实现的？

我们的矢量瓦片中只有填色图的多边形数据，每天我们从后台拿到的数据是每个多边形对应的值：比如 `武汉:40`,`南昌:10`, 然后通过Express去设置每个矢量多边形的颜色。新建的时候使用类似如下的style
```
map.addLayer(
    {
        'id': `cn-shi`,
        'type': 'fill',
        'source': 'composite',
        'source-layer': 'cn_shi_polygon',
        'paint': {
            'fill-color': [
                "match", // 匹配名字和颜色
                [
                    "get",
                    "name" // 获取瓦片中的polygon的名字
                ],
                "湖北", 
                "rgba(204,30,29,1)",
                "广东",
                "rgba(239,63,63,1)",
                "河南",
                "rgba(239,63,63,1)",
                "rgba(239,63,63,1)"
            ]
        },
    },
    'cn-shiboundary-line'
);
```
切换数据的时候只要通过`setPainProperty`方法设置新的值即可 (注意Id要和之前addlayer的id一致)
```
map.setPaintProperty(`cn-shi`, 'fill-color', [
    "match", // 匹配名字和颜色
    [
        "get",
        "name" // 获取瓦片中的polygon的名字
    ],
    "湖北",
    "red",
    "广东",
    "black",
    "河南",
    "yellow",
    "blue"
]);
```

####  3.原始数据能否共享？

原始数据暂时不能共享，如需学习研究可以通过浏览器的开发者工具观察请求返回的数据结构和内容。
