### ISSUE TITLE
地图如何转换成中文标注

### ISSUE THREAD

**Issue by zzwwzz0401** [zmofei/coronavirus-2019-demo#10]

**Comment by zmofei** [comment]
在style中有field的配置，可以通过该字段将标注转换成中文。
可以先看一下文档 https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-text-field

**Comment by zzwwzz0401** [comment]
this.map.setLayoutProperty('country-label', 'text-field',.......用这种方式只能转换国家中文，怎么转省份和城市的呢

**Comment by zzwwzz0401** [comment]
this.map.setLayoutProperty('country-label',&nbsp;'text-field',&nbsp;['format',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;['get',&nbsp;'name_zh'],&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'font-scale':&nbsp;1.2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'\n',&nbsp;{},
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;['get',&nbsp;'name'],&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'font-scale':&nbsp;0.8,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'text-font':&nbsp;['literal',&nbsp;['DIN&nbsp;Offc&nbsp;Pro&nbsp;Italic',&nbsp;'Arial&nbsp;Unicode&nbsp;MS&nbsp;Regular']]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;])


我用这种方法只能转换国家的中文，知道是因为‘country-label’，怎样转省份和城市的呢？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mofei Zhu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月21日(星期天) 晚上11:35
收件人:&nbsp;"zmofei/coronavirus-2019-demo"<coronavirus-2019-demo@noreply.github.com&gt;;
抄送:&nbsp;"庄梓炜"<826624508@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zmofei/coronavirus-2019-demo] 地图如何转换成中文标注 (#10)





 
在style中有field的配置，可以通过该字段将标注转换成中文。
 可以先看一下文档 https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-text-field

**Comment by zmofei** [comment]
可以通过下面的方法找到省份和城市有没有中文字段，如果有的话，把`text-field`直接切换成对应的字段即可
```
map.on('click', (e: any) => {
    const features = map.queryRenderedFeatures(e.point);
    if (features.length > 0) {
        console.log(features);
    }
});
```
