### ISSUE TITLE
请问heat map如何随着缩放地图而改变

### ISSUE THREAD

**Issue by zk3303** [zmofei/coronavirus-2019-demo#2]
在mapbox studio 的style中 tyle选择了heatmap 调整过radlus.但是缩小看不到。 只有放大才能看到。

**Comment by zmofei** [comment]
你好，请问是否调整过 readis和zoom 的关系？
![image](https://user-images.githubusercontent.com/3351337/76530002-0a699480-64ae-11ea-9c72-a7e7bcac8680.png)

可以截张图给我，或者点击右下角的`Edit json`按钮把对应的配置发出来看一下。
![image](https://user-images.githubusercontent.com/3351337/76530110-338a2500-64ae-11ea-94d2-579805431497.png)

**Comment by zk3303** [comment]
![1](https://user-images.githubusercontent.com/62102187/76535661-80083d00-647b-11ea-8ab5-882edc45b6ee.png)
![2](https://user-images.githubusercontent.com/62102187/76535669-839bc400-647b-11ea-8f77-6fcecacc7e80.png)
只差了1的px. 并不是缩小 而是消失

**Comment by zmofei** [comment]
截图中看不出来地图的缩放级别，想问一下数据本身是完整的么？ 会不会是因为数据只有部分区域的，缩小之后就成了现在截图上的样子？

**Comment by zk3303** [comment]
这是mapbox自带的 操作为New layer-Mapbox streets V8-building-tyle-heat map
![image](https://user-images.githubusercontent.com/62102187/76619816-0c723880-652c-11ea-93d3-aaa7711c74f2.png)

**Comment by zk3303** [comment]
在网上看到了这种 请问 是不是只能自己爬数据 然后用其他方式去做
![image](https://user-images.githubusercontent.com/62102187/76620426-66bfc900-652d-11ea-8340-e620ba94a4e8.png)

**Comment by zmofei** [comment]
@zk3303 
Mapbox v8 数据源中的building只有在zoom > 13的时候才会有，所以地图缩小之后是看不见的。
https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/#building
![image](https://user-images.githubusercontent.com/3351337/76628870-66005480-6578-11ea-9e18-fa2a9d4513ba.png)

上面的图需要自己有数据才能倒入到studio中去用

**Comment by zk3303** [comment]
谢谢大神指点！
