### ISSUE TITLE
获取填色地图的面坐标以及上传到studio这个能做个教程吗

### ISSUE THREAD

**Issue by karizzle0701** [zmofei/coronavirus-2019-demo#4]
获取填色地图的面坐标以及上传到studio这个能做个教程吗

**Comment by macro-shen** [comment]
@karizzle0701 - 在对地图的面图层进行填色，不需要获取切片中的面的坐标，可以根据切片中数据的属性 来 跟动态数据进行绑定：使用mapbox gl js中的`map.setFeatureState`方法， 参考：https://docs.mapbox.com/mapbox-gl-js/api/#map#setfeaturestate 

也可以参考我们的其他教程：https://docs.mapbox.com/help/tutorials/data-joins-with-mapbox-boundaries/

数据上传到studio 在官网有很多教程：https://docs.mapbox.com/studio-manual/overview/geospatial-data/#preparing-your-data-for-upload
