### ISSUE TITLE
整个项目能开源吗

### ISSUE THREAD

**Issue by topwood** [zmofei/coronavirus-2019-demo#5]
https://www.mapbox.cn/coronavirusmap

**Comment by zmofei** [comment]
??????????????????????????????On Mon, Mar 16, 2020 at 11:55 liz <notifications@github.com> wrote:

????????



?You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zmofei** [comment]
目前还不行，不过如果你有什么问题，可以直接问，能回答的我都会回答的，谢谢
