### ISSUE TITLE
关于数字面板的问题

### ISSUE THREAD

**Issue by qqme306** [zmofei/coronavirus-2019-demo#6]
请问页面的数字面板模块的样式是引用哪个控件吗？官方有提供吗？好像没看到。

**Comment by zmofei** [comment]
你好，数字面板非官方控件，可以根据自己的需求来实现。

**Comment by qqme306** [comment]
能分享一下怎么做吗？包括几个面板的点击效果，交互，觉得很酷炫。都是怎么实现的纯CSS写的还是通过什么技术手段。新手小白，望见谅。

**Comment by zmofei** [comment]
@qqme306 面板涉及到的功能很多，你可以把你关注的功能截图或者详细描述一下，我可以针对性的进行解答

**Comment by zmofei** [comment]
你好，面板中的时间控件已经开源 https://github.com/zmofei/timeplayer/
具体的实现方法可以看我的公众号文章 https://mp.weixin.qq.com/s/-ocysgoPgnvey8s2hvG06Q

**Comment by qqme306** [comment]
![image](https://user-images.githubusercontent.com/16029732/77599253-1722c980-6f3f-11ea-9b3d-05ee4f8734bc.png)
比如说这个历史曲线，我关注的是，他的样式、点击关闭效果，字体，以及他如何分布在页面的这个位置。是自己一点点写的，还是引用了什么控件。因为最早的时候自己写过一次，无法达到这么酷炫的效果，自己写起来很山寨，交互感觉也不平顺。

**Comment by zmofei** [comment]
曲线是使用 echarts 实现的，你可以参考下面的网址
https://www.echartsjs.com/en/index.html
