### ISSUE TITLE
时间穿梭模块可以开源出来吗?谢谢!

### ISSUE THREAD

**Issue by zzuisa** [zmofei/coronavirus-2019-demo#7]

**Comment by zmofei** [comment]
你好，根据之前的功能，我重新写了一个开源的时间控件 https://github.com/zmofei/timeplayer/ 
具体的实现方法可以看我的公众号文章 https://mp.weixin.qq.com/s/-ocysgoPgnvey8s2hvG06Q

**Comment by zzuisa** [comment]
感谢大佬!!!

**Comment by zzuisa** [comment]
另外想问一下,在mapbox中如何去调整图层之间的z-index呢, 比如显示的聚合数据被地图上的 地区名称挡住了, 如何设置才能让聚合的图层显示在上方呢, 看了下api但是还是没有找到解决方案.
![image](https://user-images.githubusercontent.com/38583861/77857393-6007a600-71fd-11ea-8073-7d72fbc84923.png)

**Comment by zmofei** [comment]
可以关注一下 `addlayer` 和 `movelayer` 两个方法的第二个参数，这个参数指定新的图层或者移动后的图层的位置。
https://docs.mapbox.com/mapbox-gl-js/api/#map#addlayer 
https://docs.mapbox.com/mapbox-gl-js/api/#map#movelayer

**Comment by zzuisa** [comment]
哇,感谢,还是自己看的不够仔细呀!
