### ISSUE TITLE
数据面板是如何实现的？

### ISSUE THREAD

**Issue by 6creative6** [zmofei/coronavirus-2019-demo#9]
请问截图这部分“累计数据”的展示面板，是使用哪个控件实现的？谢谢
![image](https://user-images.githubusercontent.com/17619357/81886960-a3ad4800-95d0-11ea-8475-ffb89631c41b.png)

**Comment by zmofei** [comment]
??????????6creative6 <notifications@github.com>?2020?5?14? ??10:51???

????????????????????????????????





?You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zmofei** [comment]
这部分的功能是自己写的，没有用控件
